version: '3.8'

services:
  api:
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=4000
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - OLLAMA_TEMPERATURE=0.2
      - OLLAMA_TIMEOUT=30000
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/dist
    networks:
      - chatbot-network

  web:
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/dist
    networks:
      - chatbot-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - chatbot-network
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  chatbot-network:
    driver: bridge 